### PR TITLE
login attempts are now logged

### PR DESCRIPTION
**Pull request by philippks**
Logs attempts to login and displays them on the main view:
image

Plus Index for Login Attempts:
image

### CODE REVIEW

**Comment by pencil** [comment]
Thanks, this looks awesome!

There is one minor problem: Usernames in CASino are not unique. Technically the same username can be used by different authentication backends. I see two possible solutions for this:

a) No longer allow duplicated usernames and make them unique. This would require a new major release since it's not backward compatible.
b) Log failed login attempts to all existing user account. Log successful attempts to the actual account that logged in.

**Comment by philippks** [comment]
Hey @pencil, thank you for your feedback!

In my opinion the proper solution would be to make the usernames unique, as you proposed. I cannot think of a reasonable use case to have the same username on different authenticators, since the same username should be the same user.

Do you agree? Then I would commit the corresponding changes.

**Comment by calmyournerves** [comment]
@pencil did you already have a chance to look at this again? Thanks!

**Comment by pencil** [comment]
Awesome, thanks.

**Pull request merged**
